In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import matplotlib.image as mpimage
from PIL import Image
import numpy as np
import os
import random
from sklearn import ensemble,preprocessing
import keras.utils.np_utils


Bad key text.latex.preview in file C:\Users\defaultuser0\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 123 ('text.latex.preview : False')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template
or from the matplotlib source distribution

Bad key mathtext.fallback_to_cm in file C:\Users\defaultuser0\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 155 ('mathtext.fallback_to_cm : True  # When True, use symbols from the Computer Modern')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.5.1/matplotlibrc.template
or from the matplotlib source distribution

Bad key savefig.jpeg_quality in file C:\Users\defaultuser0\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 418 ('savefig.jpeg_quality: 95       # when a jpeg is saved, the default quality p

In [2]:
# path = "./Sample/Train_Full_Data/"
path = "./acmcheck/"


folders = os.listdir(path)
imageList=[]
imageMatrix = []
newIm = []
labels=[]
# Get list of folders in current path
for folder in folders:
    newPath = path + folder  #Create new path by adding folder name
    folderName = os.path.split(os.path.abspath(newPath))[1]
    characterName = folderName.split("_")[2]
    imageList=[f for f in os.listdir(newPath) if os.path.splitext(f)[-1] == '.png'] #Check if PNG files only then add
    for image in imageList:   #Traverse the list of files and add each file name to the imageFile
        im = Image.open(newPath+"//"+image)
        labels.append(characterName)
        imageArray = np.asarray(im.getdata())
        flattenedImageArray = imageArray.flatten()
        imageMatrix.append(flattenedImageArray)
print("Size of the image matrix = ",np.size(imageMatrix))

Size of the image matrix =  46899200


In [3]:
a = np.array(imageMatrix)
a
print(a.shape)

(45800, 1024)


In [4]:
#define variables
n_samples = len(a)
X = a.reshape((n_samples,-1))
T = np.array(labels)
print('Features size = ',X.shape)
print('Labels size = ',T.shape)
print(T)


Features size =  (45800, 1024)
Labels size =  (45800,)
['gya' 'gya' 'gya' ... 'adna' 'adna' 'adna']


In [5]:
np.unique(T), len(np.unique(T))

(array(['adna', 'ba', 'bha', 'cha', 'chha', 'chhya', 'da', 'daa', 'dha',
        'dhaa', 'ga', 'gha', 'gya', 'ha', 'ja', 'jha', 'ka', 'kha', 'kna',
        'la', 'ma', 'motosaw', 'na', 'pa', 'patalosaw', 'petchiryakha',
        'pha', 'ra', 'taamatar', 'tabala', 'tha', 'thaa', 'tra', 'waw',
        'yaw', 'yna'], dtype='<U12'), 36)

In [6]:
le=preprocessing.LabelEncoder()
le.fit(T)
T=le.transform(T)

T=keras.utils.np_utils.to_categorical(T)

In [7]:
le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print(le_name_mapping)

{'adna': 0, 'ba': 1, 'bha': 2, 'cha': 3, 'chha': 4, 'chhya': 5, 'da': 6, 'daa': 7, 'dha': 8, 'dhaa': 9, 'ga': 10, 'gha': 11, 'gya': 12, 'ha': 13, 'ja': 14, 'jha': 15, 'ka': 16, 'kha': 17, 'kna': 18, 'la': 19, 'ma': 20, 'motosaw': 21, 'na': 22, 'pa': 23, 'patalosaw': 24, 'petchiryakha': 25, 'pha': 26, 'ra': 27, 'taamatar': 28, 'tabala': 29, 'tha': 30, 'thaa': 31, 'tra': 32, 'waw': 33, 'yaw': 34, 'yna': 35}


In [8]:
new_model = tf.keras.models.load_model('my_model1')
# new_model.summary()

In [9]:
type(X), 

(numpy.ndarray,)

In [10]:
new_model.predict(X[0].reshape(1, 32, 32, 1))

array([[6.0936542e-21, 3.5730777e-20, 5.8994248e-26, 2.4052369e-28,
        1.5951901e-27, 2.2187842e-14, 2.5397832e-31, 9.0390180e-28,
        4.9993116e-27, 5.8806837e-34, 3.2785901e-20, 9.5758741e-30,
        1.0000000e+00, 7.1312094e-31, 6.2670862e-12, 2.2419935e-30,
        4.7793747e-27, 1.2189585e-25, 7.9811141e-26, 6.2084097e-15,
        4.8049270e-21, 5.3401939e-16, 1.4911544e-09, 5.8805478e-27,
        1.6394154e-21, 3.3337551e-27, 1.7291242e-30, 1.0547344e-27,
        4.8063594e-35, 6.7912200e-22, 8.3920606e-28, 2.3914981e-33,
        3.0573844e-18, 6.2780891e-17, 3.7347035e-31, 9.4056358e-17]],
      dtype=float32)

In [11]:
def get_output(output, i):
    greatest = output[0][0]
    pos = 0
    for i in range(len(output[0])): 
        if greatest < output[0][i]:
            greatest = output[0][i]
            pos = i  
#     print(greatest, pos)
    output = [0.]*36
    output[pos] = 1.
    predicted = np.asarray(output)
#     print(np.unique(labels)[pos])
#     plt.imshow(X[i].reshape(32, 32))
#     print(T[i])
#     print(predicted)
    result = T[i] == predicted
    return result.all() 

# i =10000
# o1 = new_model.predict(X[i].reshape(1, 32, 32, 1))     
# get_output(o1, i)

correct_prediction = 0 
for i in range(X.shape[0]):  
    o1 = new_model.predict(X[i].reshape(1, 32, 32, 1))
    if get_output(o1, i):
        correct_prediction += 1
    if i==2300:
        break 

# 

In [12]:
correct_prediction

1629

In [13]:
# (correct_prediction/X.shape[0]) * 100
(correct_prediction/2300) * 100

70.82608695652173

In [14]:
new_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 30, 30, 4)         40        
                                                                 
 conv2d_1 (Conv2D)           (None, 28, 28, 4)         148       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 14, 14, 4)        0         
 )                                                               
                                                                 
 conv2d_2 (Conv2D)           (None, 12, 12, 4)         148       
                                                                 
 conv2d_3 (Conv2D)           (None, 10, 10, 4)         148       
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 5, 5, 4)          0         
 2D)                                                    

In [15]:
a = [1., 0., 1.]
np.asarray(a), list(np.asarray(a))

(array([1., 0., 1.]), [1.0, 0.0, 1.0])

In [16]:
np.asarray(a)

array([1., 0., 1.])